# FROM ubuntu:focal
FROM nvidia/cuda:11.6.0-devel-ubuntu20.04

# installing packages required for installation
RUN echo "downloading basic packages for installation"
RUN apt-get update
RUN apt-get install -y tmux wget curl git
RUN apt-get install -y libstdc++6 gcc

# checking installation of tools
RUN gcc --version
RUN nvcc --version

# clone git repository
RUN git clone https://github.com/awesome-bio/lab-alphafold.git

# download instructions from YoshitakaMo localcolabfold work
RUN echo "downloading instructions and starting install"
RUN wget https://raw.githubusercontent.com/YoshitakaMo/localcolabfold/main/install_colabbatch_linux.sh

# install colabfold
# RUN cd lab-alphafold
RUN bash install_colabbatch_linux.sh

# complete installation

